# Stage 1 - Build frontend

FROM node:20-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./

RUN npm ci --legacy-peer-deps
COPY frontend .

RUN npm run build

# Stage 2 - Nginx serving
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
